# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Uses Gemini to clean up warning exemptions for a set of git repos."""

import argparse
import concurrent.futures
import dataclasses
import logging
from pathlib import Path
import subprocess
import sys

from android_tools import android_paths
from android_tools import parse_and_apply_warning_exemptions as parse_and_apply
from cros_utils import git_utils


@dataclasses.dataclass(frozen=True)
class RunConfig:
    """Shared attributes between clean-up runs."""

    android_tree: Path
    gemini_prompt: str


def read_gemini_prompt() -> str:
    prompt_md = (
        android_paths.script_toolchain_utils_root()
        / "android_tools"
        / "clean_warning_exemptions_prompt.md"
    )
    return prompt_md.read_text(encoding="utf-8")


def run_on_repo(config: RunConfig, git_repo: Path) -> bool:
    """Runs on a git repo, returning True if changes were made."""

    logging.info("Running Gemini on %s...", git_repo)
    git_repo_path = config.android_tree / git_repo

    head_contents = git_utils.format_patch(git_repo_path, "HEAD")
    # Use gemini-cli rather than Gemini's API, since gemini-cli has the built-in
    # ability to edit files/etc.
    run_result = subprocess.run(
        (
            "gemini",
            # This isn't an interactive session; approve all edits, but stop
            # short of running anything else.
            "--approval-mode=auto_edit",
            "\n".join((config.gemini_prompt, head_contents)),
        ),
        cwd=git_repo_path,
        check=False,
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        encoding="utf-8",
        errors="replace",
    )

    if run_result.returncode:
        logging.error(
            "Gemini failed on %s; stdout/stderr:\n%s",
            git_repo,
            run_result.stdout,
        )
        run_result.check_returncode()

    logging.debug("Gemini's output on %s was:\n%s", git_repo, run_result.stdout)

    # Gemini is instructed to only make changes to files, and has no ability to
    # use tools like `git`. So if there's a diff, it made changes.
    if not git_utils.has_discardable_changes(git_repo_path):
        logging.info("Gemini made no changes to %s.", git_repo)
        return False

    new_sha = git_utils.amend_head_with_all_changes(git_repo_path, quiet=True)
    logging.info(
        "Committed Gemini's changes to %s; new HEAD is %s.", git_repo, new_sha
    )
    return True


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--debug", action="store_true", help="Enable debug logging"
    )
    parser.add_argument(
        "--android-tree",
        type=Path,
        help="""
        Android tree to modify. If not specified, autodetection from this
        script's directory will be attempted.
        """,
    )
    parser.add_argument(
        "--jobs", type=int, default=8, help="Max jobs to run at once."
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--only-repo",
        type=Path,
        help="""
        Only run on the repository given here. This repository should be
        relative to the Android root, e.g., `bionic/`.
        """,
    )
    group.add_argument(
        "--summary-file",
        type=Path,
        help="""
        The --update-summary-file generated by the warning suppression script.
        """,
    )
    return parser.parse_args(argv)


def main(argv: list[str]) -> None:
    opts = parse_args(argv)
    logging.basicConfig(
        format=">> %(asctime)s: %(levelname)s: %(filename)s:%(lineno)d: "
        "%(message)s",
        level=logging.DEBUG if opts.debug else logging.INFO,
    )

    android_tree: Path = (
        opts.android_tree or android_paths.script_android_checkout_or_exit()
    )
    summary_file_path: Path = opts.summary_file
    only_repo: Path | None = opts.only_repo

    if only_repo:
        only_repo_git_dir = android_tree / only_repo / ".git"
        if not only_repo_git_dir.exists():
            sys.exit(
                f"Path at {only_repo_git_dir} doesn't exist; check that "
                "`--only-repo`'s value is correct."
            )

        repos_to_run_on = [only_repo]
    else:
        summary_file = parse_and_apply.ExemptionSummary.from_file(
            summary_file_path
        )
        repos_to_run_on = summary_file.git_dirs

    run_config = RunConfig(
        android_tree=android_tree,
        gemini_prompt=read_gemini_prompt(),
    )

    with concurrent.futures.ThreadPoolExecutor(opts.jobs) as thread_pool:
        futures = []
        for r in repos_to_run_on:
            f = thread_pool.submit(
                run_on_repo,
                run_config,
                r,
            )
            futures.append((r, f))

        exceptions = []
        num_successful_updates = 0
        for repo, run_result in futures:
            if e := run_result.exception():
                exceptions.append((repo, e))
            elif run_result.result():
                logging.info("Successfully updated %s", repo)
                num_successful_updates += 1

        # Log exceptions in a batch afterward, so they don't get lost in any
        # logging output above.
        for repo, e in exceptions:
            logging.error(
                "Exception caught making changes to %s", repo, exc_info=e
            )

        logging.info("Applied updates to %d repos", num_successful_updates)
        sys.exit(1 if exceptions else 0)


if __name__ == "__main__":
    main(sys.argv[1:])
