# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Parses and applies warning exemptions from a build log.

For example, let's say that you had the build log of an Android build in
/tmp/build.log (in the form of a log generated by `m >& /tmp/build.log`, or
unpacking `verbose.log`, or similar).

If you invoke this script like:

$ py/bin/android_tools/parse_and_apply_warning_exemptions \
    --android-tree=/path/to/android/tree/root \
    --bug-number=1234 \
    --build-log=/tmp/build.log \
    --upload-with-topic=my-warning-suppressions \
    --update-summary-file=/tmp/summary.json

It will:

1. Parse your build log for warnings that will soon be fatal.
2. Modify all `bp` targets that will be impacted.
3. Create commits w/ helpful messages (tagged with b/1234) in all git repos
   that were modified.
4. Upload all changes to the git repos from step #3, tagged with the
   `my-warning-suppressions` topic.
5. Write a summary file of all changed projects/targets to `/tmp/summary.json`,
   for further automation.
"""

import argparse
import collections
import concurrent.futures
import dataclasses
import json
import logging
import os
from pathlib import Path
import re
import shlex
import subprocess
import sys
import textwrap
import threading
from typing import DefaultDict, Iterable, Self, Sequence

from android_tools import android_paths
from android_tools import bp_tools
from android_tools import warning_suppression
from cros_utils import git_utils
from llvm_tools import warning_exemption


def infer_target_from_cmdline(command: list[str]) -> str | None:
    try:
        dash_o_index = command.index("-o")
    except ValueError:
        return None

    # Any well-formed compiler command will have a target after -o
    output_file = command[dash_o_index + 1]

    # Soong's output names look like:
    #   out/soong/.intermediates/
    #   ${target_path_from_top_of_tree}/
    #   ${variant}/
    #   obj/
    #   ${path_of_input_files_dir}/
    #   ${basename_of_input_file_no_ext}.o
    #
    # For example,
    # out/soong/.intermediates/bionic/libc/libc_bionic/
    #   android_x86_silvermont_static_apex10000_sabi/obj/bionic/libc/bionic/
    #   sigprocmask.o
    # has:
    #  - target_path_from_top_of_tree == //bionic/libc:libc_bionic
    #  - variant == android_x86_silvermont_static_apex10000_sabi
    #  - path_of_input_files_dir == obj/bionic/libc/bionic
    #  - basename_of_input_file_no_ext == sigprocmask
    prefix = "out/soong/.intermediates/"
    if not output_file.startswith(prefix):
        logging.warning(
            "Can't infer cmdline target; output file %s doesn't start with %s",
            output_file,
            prefix,
        )
        return None

    obj_location = output_file.find("/obj/")
    if obj_location == -1:
        logging.warning(
            "Can't infer cmdline target; output file %s has no /obj/",
            output_file,
        )
        return None

    # b/476408642#comment11 (and following comments): All HIDL builds should
    # conform to all of the above, but the hidl `cc_library` target is
    # synthesized to have _the same name_ as the corresponding `hidl_interface`
    # target.
    #
    # `hidl_interface` targets can't have cflags added, and all of the generated
    # code is seemingly the responsibility of the hidl maintainers, so have a
    # special case here to return the `cc_defaults` that all hidl-synthesized
    # `cc_library`s inherit.
    if warning_suppression.HIDL_BUILD_MARKER_FLAG in command:
        return warning_suppression.HIDL_DEFAULTS_TARGET

    target_path_and_variant = output_file[len(prefix) : obj_location]
    target_path_no_colon = os.path.dirname(target_path_and_variant)
    target_path, target_name = target_path_no_colon.rsplit("/", 1)
    return f"//{target_path}:{target_name}"


def parse_one_warning_report(
    report_line: str,
    report_line_number: int,
) -> tuple[str, warning_exemption.FatalWarningGroup] | None:
    report_json = json.loads(report_line)
    parsed_warnings = warning_exemption.scrape_fatal_warnings_from_stdout(
        report_json["stdout"]
    )

    # The shape of warnings_json is:
    # {
    #   "cwd": "/path/to/directory",
    #   "command": ["ccache", "full", "compile", "command"],
    #   "stdout": "stdout/stderr of the build",
    #   "parent_process_data": [
    #     {
    #       "invocation": ["parent", "process", "command"],
    #       "env": ["ENV1=", "ENV2=value", ""]
    #     }
    #   ]
    # }
    if not parsed_warnings:
        logging.warning(
            "Found no fatal warnings from report on line %d; ignoring",
            report_line_number,
        )
        return None

    target = infer_target_from_cmdline(report_json["command"])
    if not target:
        logging.warning(
            "Could not infer target from report on line %d; ignoring",
            report_line_number,
        )
        return None

    result_lines = {x for x, _ in parsed_warnings}
    result_names = {x for _, x in parsed_warnings}
    return target, warning_exemption.FatalWarningGroup(
        result_names, result_lines
    )


def parse_warning_reports(
    build_log: Path,
) -> dict[str, warning_exemption.FatalWarningGroup]:
    """Parses a build log for fatal warning reports.

    Returns:
        A dict of fatal warnings. Strings are paths to targets.
    """
    per_package_groups: DefaultDict[
        str, warning_exemption.FatalWarningGroup
    ] = collections.defaultdict(warning_exemption.FatalWarningGroup)
    # These are stored in the build log as single lines, like:
    # ```
    # <LLVM_NEXT_ERROR_REPORT>{"json": "object"}</LLVM_NEXT_ERROR_REPORT>
    # ```
    # The `{"json": "object"}` is what ChromeOS stores in individual warning
    # report files.
    werror_report_start = "<LLVM_NEXT_ERROR_REPORT>"
    werror_report_end = "</LLVM_NEXT_ERROR_REPORT>"

    werror_report_start_bin = werror_report_start.encode()
    werror_report_end_bin = werror_report_end.encode()
    with build_log.open("rb") as f:
        num_invalid_lines = 0
        for line_number, raw_line in enumerate(f, 1):
            try:
                line = raw_line.decode("utf-8")
            except UnicodeDecodeError:
                # There are observably quite a few UTF-8 decode errors in build
                # logs.
                #
                # If the line seems inconsequential, just add to a counter. If
                # it seems consequential, log a warning.
                if (
                    werror_report_start_bin in raw_line
                    or werror_report_end_bin in raw_line
                ):
                    logging.warning(
                        "Dropping interesting line (line number %d) due to "
                        "invalid UTF-8.",
                        line_number,
                    )
                else:
                    num_invalid_lines += 1
                continue

            line = line.strip()
            if not line.startswith(werror_report_start):
                continue

            if not line.endswith(werror_report_end):
                logging.warning(
                    "Line %d had error report start tag without end tag; "
                    "ignoring",
                    line_number,
                )
                continue

            logging.debug("Processing report on line %d", line_number)
            line = line[len(werror_report_start) : -len(werror_report_end)]
            parse_result = parse_one_warning_report(line, line_number)
            if not parse_result:
                # This should've been logged by the callee, so don't log.
                continue

            package, warnings_group = parse_result
            per_package_groups[package].add(warnings_group)

    if num_invalid_lines:
        logging.info(
            "%d uninteresting lines dropped due to invalid UTF-8",
            num_invalid_lines,
        )

    return per_package_groups


def group_targets_by_bp_file(
    targets: Iterable[str],
) -> dict[Path, list[tuple[str, str]]]:
    results = collections.defaultdict(list)
    for target in targets:
        pieces = target.split(":")
        if len(pieces) != 2:
            raise ValueError(f"Invalid target: {target}")
        android_bp_dir, target_name = pieces
        results[Path(android_bp_dir.lstrip("/"), "Android.bp")].append(
            (target_name, target)
        )
    return results


def checked_subprocess_run(
    cmd: Sequence[Path | str],
    *,
    cwd: Path | None = None,
    input_str: str | None = None,
) -> str:
    """Runs cmd, logging stdout/stderr and `raise`ing on error.

    Returns:
        stdout+stderr as one stream
    """
    result = subprocess.run(
        cmd,
        check=False,
        cwd=cwd,
        stdin=None if input_str else subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        input=input_str,
        encoding="utf-8",
        errors="replace",
    )
    if not result.returncode:
        return result.stdout

    logging.error(
        "Failed to run `%s`; stdout/stderr:\n%s",
        shlex.join(str(x) for x in cmd),
        result.stdout,
    )
    result.check_returncode()
    assert False, "unreachable"


@dataclasses.dataclass(frozen=True)
class ApplyWarningExemptionsResult:
    """Results of `apply_warning_exemptions`."""

    successfully_updated_files: list[Path] = dataclasses.field(
        default_factory=list
    )
    update_failures: int = 0
    updated_targets: dict[str, list[str]] = dataclasses.field(
        default_factory=dict
    )


@dataclasses.dataclass(frozen=True)
class BpExemptionSummary:
    """A summary of exemptions for a single Android.bp file."""

    per_target_warnings: dict[str, list[str]] = dataclasses.field(
        default_factory=dict
    )


@dataclasses.dataclass(frozen=True)
class RepoExemptionSummary:
    """A summary of exemptions for a single repo."""

    updated_files: dict[str, BpExemptionSummary] = dataclasses.field(
        default_factory=dict
    )
    uploaded_cl: str | None = None


@dataclasses.dataclass(frozen=True)
class ExemptionSummary:
    """A summary of exemptions that were applied."""

    bug_number: int
    exemptions: dict[str, RepoExemptionSummary] = dataclasses.field(
        default_factory=dict
    )

    @classmethod
    def from_file(cls, path: Path) -> Self:
        """Loads an ExemptionSummary from the given file."""
        with path.open(encoding="utf-8") as f:
            content = json.load(f)

        exemptions = {}
        for repo_path, repo_data in content["exemptions"].items():
            updated_files = {}
            for bp_path, bp_data in repo_data["updated_files"].items():
                updated_files[bp_path] = BpExemptionSummary(
                    per_target_warnings=bp_data["per_target_warnings"]
                )

            exemptions[repo_path] = RepoExemptionSummary(
                updated_files=updated_files,
                uploaded_cl=repo_data.get("uploaded_cl"),
            )

        return cls(
            bug_number=content["bug_number"],
            exemptions=exemptions,
        )

    def write_to_file(self, path: Path) -> None:
        """Writes this ExemptionSummary to the given file."""
        output_exemptions = {}
        for repo_path, summary in self.exemptions.items():
            repo_files = {}
            for bp_path, bp_summary in summary.updated_files.items():
                repo_files[bp_path] = {
                    "per_target_warnings": bp_summary.per_target_warnings
                }
            output_exemptions[repo_path] = {
                "updated_files": repo_files,
                "uploaded_cl": summary.uploaded_cl,
            }

        with path.open("w", encoding="utf-8") as f:
            json.dump(
                {
                    "bug_number": self.bug_number,
                    "exemptions": output_exemptions,
                },
                f,
                sort_keys=True,
                indent=2,
                separators=(",", ": "),
            )
            # Ensure a newline at the end; many editors want it.
            f.write("\n")


_HUNK_LINE_COUNT_REGEX = re.compile(r"([-+]\d+),(\d+)")


def update_hunk_header_for_added_lines(
    hunk_header: str,
    added_lines: int,
    preexisting_added_lines: int,
) -> str:
    """Updates a hunk header to add `added_lines`.

    >>> update_hunk_header_for_added_lines(
            "@@ -5,12 +5,18 @@",
            added_lines=2,
            preexisting_added_lines=4,
        )
    "@@ -5,12 +9,20 @@"

    Args:
        hunk_header: header to update.
        added_lines: number of lines added to this hunk.
        preexisting_added_lines: number of lines added to the diff before this
            hunk.
    """
    # Hunk headers are formatted like:
    # @@ -5,12 +6,18 @@
    #
    # This means:
    # - This hunk begins at line 5 of the old file.
    # - The old file has 12 lines represented in this hunk.
    # - This hunk begins at line 6 of the old file.
    # - The new file has 18 lines represented in this hunk.
    line_count_matches = list(_HUNK_LINE_COUNT_REGEX.finditer(hunk_header))
    if len(line_count_matches) != 2:
        raise ValueError(
            f"Expected 2 matches of {_HUNK_LINE_COUNT_REGEX} in "
            f"{hunk_header}; git {len(line_count_matches)}"
        )

    _, add_match = line_count_matches
    start_line_str, line_count_str = add_match.groups()
    if not start_line_str.startswith("+"):
        raise ValueError(
            f"Hunk added line {start_line_str!r} didn't start with +"
        )

    new_start_line = int(start_line_str.lstrip("+")) + preexisting_added_lines
    new_line_count = int(line_count_str) + added_lines
    new_add_match = f"+{new_start_line},{new_line_count}"
    return (
        hunk_header[: add_match.start()]
        + new_add_match
        + hunk_header[add_match.end() :]
    )


def add_suppression_comments_to_diff(
    bug_number: int,
    bpmodify_diff: str,
    exempted_literals: list[str],
) -> str:
    """Adds comments about warning suppression to the given diff.

    Only supports diffs emitted by `bpmodify`.
    """
    # This is the comment to add before every warning suppression. `bpfmt` is
    # expected to indent it properly. It's kept short because it may need to be
    # indented a fair amount, and don't want to go over the line limit.
    add_comment = f"+// Bulk-suppressed; see b/{bug_number} for details\n"

    # Since these diffs are well-formed (and have no commentary at the top), we
    # can assume that all lines are either metadata, or start with one of ("-",
    # "+", or " "). Metadata for diff hunks always starts with `"\n @@"`.
    hunk_split = "\n@@ "
    header, *hunks = bpmodify_diff.split(hunk_split)
    result_file = [header]

    preexisting_added_lines = 0
    for hunk in hunks:
        new_hunk_lines = []
        hunk_header, *rest = hunk.splitlines(keepends=True)
        added_lines = 0
        for hunk_line in rest:
            if hunk_line.startswith("+"):
                if any(x in hunk_line for x in exempted_literals):
                    added_lines += 1
                    new_hunk_lines.append(add_comment)
            new_hunk_lines.append(hunk_line)
        new_hunk_header = update_hunk_header_for_added_lines(
            hunk_header, added_lines, preexisting_added_lines
        )
        new_hunk_lines.insert(0, new_hunk_header)
        result_file.append("".join(new_hunk_lines))
        preexisting_added_lines += added_lines
    return hunk_split.join(result_file)


def add_warning_cflags(
    android_tree: Path,
    bug_number: int,
    bpmodify_bin: Path,
    bpfmt_bin: Path,
    android_bp_file: Path,
    per_target_warnings: list[tuple[str, warning_exemption.FatalWarningGroup]],
) -> None:
    for target_name, fatal_warnings in per_target_warnings:
        bpmodify_cmd: list[Path | str] = [
            bpmodify_bin,
            "-m",
            target_name,
            "-property",
            "cflags",
        ]

        exempted_literals = []
        for warning_name in sorted(fatal_warnings.warning_names):
            literal = f'"-Wno-{warning_name}"'
            exempted_literals.append(literal)
            bpmodify_cmd += (
                "-add-literal",
                literal,
            )

        bpmodify_cmd += ("-d", android_bp_file)
        bpmodify_diff = checked_subprocess_run(bpmodify_cmd, cwd=android_tree)
        # If `bpmodify` creates no diff, it will still exit successfully and
        # output a nonempty string, but there will be no actual diff hunks.
        #
        # Search for `\n--- `, since that's the first definitive sign we can
        # find of a diff hunk.
        if "\n--- " not in bpmodify_diff:
            raise ValueError(
                f"bpmodify did not create a diff to add CFLAGS to "
                f"{android_bp_file}"
            )

        fixed_diff = add_suppression_comments_to_diff(
            bug_number, bpmodify_diff, exempted_literals
        )
        try:
            checked_subprocess_run(
                ("patch", "--batch", android_bp_file),
                input_str=fixed_diff,
                cwd=android_tree,
            )
        except subprocess.CalledProcessError:
            logging.error(
                "Error patching %s with patch contents:\n%r",
                android_bp_file,
                fixed_diff,
            )
            raise

    # Neither bpmodify nor the post-processing we do guarantees that these are
    # correctly formatted, so be sure to keep them pretty.
    checked_subprocess_run((bpfmt_bin, "-w", android_bp_file), cwd=android_tree)
    logging.info("Updated exemptions in %s successfully.", android_bp_file)


def apply_warning_exemptions(
    bug_number: int | None,
    warnings: dict[str, warning_exemption.FatalWarningGroup],
    android_tree: Path | None,
    thread_pool: concurrent.futures.ThreadPoolExecutor,
    dry_run: bool,
) -> ApplyWarningExemptionsResult:
    """Applies warning exemptions based on parsed warnings."""
    if dry_run:
        for target, warning_group in warnings.items():
            sorted_warning_list = sorted(warning_group.warning_names)
            logging.info(
                "dry-run: would have suppressed warnings %s in %s",
                sorted_warning_list,
                target,
            )
        return ApplyWarningExemptionsResult()

    assert android_tree, "android_tree should be non-None if not dry-run!"
    assert bug_number, "bug_number should be non-None if not dry-run!"
    grouped_warnings = group_targets_by_bp_file(warnings)

    logging.info(
        "Spawning jobs to edit %d Android.bp file%s...",
        len(grouped_warnings),
        "" if len(grouped_warnings) == 1 else "s",
    )
    bpfmt_bin = bp_tools.bpfmt_path(android_tree)
    bpmodify_bin = bp_tools.bpmodify_path(android_tree)
    futures = []
    for warning_file, targets in grouped_warnings.items():
        per_target_warnings = []
        for target_name, full_target in targets:
            per_target_warnings.append((target_name, warnings[full_target]))
        futures.append(
            thread_pool.submit(
                add_warning_cflags,
                android_tree,
                bug_number,
                bpmodify_bin,
                bpfmt_bin,
                warning_file,
                per_target_warnings,
            )
        )

    exceptions = []
    successful_updates = []
    updated_targets: dict[str, list[str]] = {}
    for warning_file, future in zip(grouped_warnings, futures):
        if e := future.exception():
            exceptions.append((warning_file, e))
        else:
            successful_updates.append(warning_file)
            for _, full_target in grouped_warnings[warning_file]:
                updated_targets[full_target] = sorted(
                    warnings[full_target].warning_names
                )

    successful_count = len(grouped_warnings) - len(exceptions)
    if successful_count:
        logging.info(
            "Successfully updated %d file%s.",
            successful_count,
            "" if successful_count == 1 else "s",
        )

    # Queue up exceptions to print until _after_ all jobs are done. This way,
    # exceptions are prominent, compared to being interleaved with successful
    # output.
    if exceptions:
        for warning_file, e in exceptions:
            logging.error(
                "Exception caught updating %s", warning_file, exc_info=e
            )

    return ApplyWarningExemptionsResult(
        successfully_updated_files=successful_updates,
        update_failures=len(exceptions),
        updated_targets=updated_targets,
    )


def map_files_to_git_repos(
    android_tree: Path,
    thread_pool: concurrent.futures.ThreadPoolExecutor,
    files: Sequence[Path],
) -> dict[Path, Path]:
    """Returns a mapping of {file: git_repo} for the given files.

    `git_repo` is relative to `android_tree`.
    """

    def get_file_toplevel(f: Path) -> Path:
        toplevel = git_utils.find_git_repo_above((android_tree / f).parent)
        return toplevel.relative_to(android_tree)

    # These `--show-toplevel` invocations are pretty fast, but we already have a
    # thread pool anyway, so use it.
    toplevels = thread_pool.map(get_file_toplevel, files)
    return dict(zip(files, toplevels))


def extract_core_warning_name(warning_flag: str) -> str:
    """Extracts core warning name from string like '-Wno-foo' or '-Wfoo'."""
    for prefix in ("-Wno-error=", "-Werror=", "-Wno-", "-W"):
        if warning_flag.startswith(prefix):
            return warning_flag.removeprefix(prefix)
    return warning_flag


def format_exemption_commit_message(
    bug_number: int,
    warning_names: Iterable[str],
    for_soong: bool = False,
) -> str:
    """Formats a commit message for warning exemptions."""
    formatted_warnings = sorted(
        {
            f"-W{core_w}"
            for w in warning_names
            if (core_w := extract_core_warning_name(w))
        }
    )

    if not formatted_warnings:
        raise ValueError("No warnings provided")
    if len(formatted_warnings) == 1:
        desc = formatted_warnings[0]
    else:
        desc = f"{len(formatted_warnings)} warnings"

    prefix = "cc: set no-error for " if for_soong else "mass-exempt "
    subject = f"{prefix}{desc}"

    warnings_section = (
        ["Warnings exempted:", *(f"- {w}" for w in formatted_warnings), ""]
        if len(formatted_warnings) > 1
        else []
    )

    if for_soong:
        explanation = [
            "Set -Wno-error for these temporarily in case CI didn't catch",
            "everything. See go/android-llvm-warning-suppression for",
            "more details.",
            "",
            f"Bug: {bug_number}",
            "Test: TreeHugger",
        ]
    else:
        explanation = [
            "Warnings will soon be introduced here due to a larger change.",
            "Preemptively suppress those. Please see the bug or contact the",
            "author for more information & notes on how to remove these",
            "suppressions.",
            "",
            "Use 'EXEMPT BUGFIX' for Flag, since this CL only disables",
            "warnings (soon to be build errors, if not for this CL) here.",
            "It would be nice to fix these, but disabling them is a nop.",
            "",
            f"Bug: {bug_number}",
            "Test: TreeHugger",
            "Flag: EXEMPT BUGFIX",
        ]

    body_lines = (
        subject,
        "",
        *warnings_section,
        *explanation,
    )
    return "\n".join(body_lines) + "\n"


def map_repos_to_warnings(
    updated_targets: dict[str, list[str]],
    file_to_repo: dict[Path, Path],
) -> dict[Path, set[str]]:
    """Maps repo paths to the set of warnings exempted within them."""
    bp_to_targets = group_targets_by_bp_file(updated_targets)
    repo_to_warnings: dict[Path, set[str]] = collections.defaultdict(set)
    for bp_path, target_tuples in bp_to_targets.items():
        repo = file_to_repo[bp_path]
        for _, full_target in target_tuples:
            repo_to_warnings[repo].update(updated_targets[full_target])
    return repo_to_warnings


def commit_new_exemptions(
    bug_number: int,
    android_tree: Path,
    thread_pool: concurrent.futures.ThreadPoolExecutor,
    updated_android_bp_files: list[Path],
    branch_name: str,
    file_to_repo: dict[Path, Path],
    updated_targets: dict[str, list[str]],
) -> list[Path]:
    """Commits all new exemptions.

    Returns:
        A list of Git repos where a commit was made, relative to android_tree.
    """
    rel_git_repos = sorted({file_to_repo[f] for f in updated_android_bp_files})
    git_repos = [android_tree / x for x in rel_git_repos]

    repo_to_warnings = map_repos_to_warnings(updated_targets, file_to_repo)

    def do_commit(repo: Path) -> None:
        rel_repo = repo.relative_to(android_tree)
        warnings = repo_to_warnings.get(rel_repo)
        if not warnings:
            raise ValueError(f"No warnings found for repository {rel_repo}")
        message = format_exemption_commit_message(bug_number, warnings)
        git_utils.commit_all_changes(
            git_dir=repo,
            message=message,
            quiet=True,
        )
        git_utils.create_branch(repo, branch_name)

    # Assume simple `git commit` commands won't fail. If they do, something
    # seems very wrong, and the program should simply abort.
    for _ in thread_pool.map(do_commit, git_repos):
        # Iteration is necessary because `map()` is lazy: it only blocks on task
        # completion _as elements are requested_. Note that `map` will reraise
        # exceptions as appropriate.
        pass
    return [x.relative_to(android_tree) for x in git_repos]


def upload_all_new_exemptions(
    android_tree: Path,
    thread_pool: concurrent.futures.ThreadPoolExecutor,
    topic: str,
    repos_to_upload: list[Path],
) -> tuple[list[Path], dict[Path, str]]:
    """Uploads all new warning exemptions.

    Returns:
        A tuple of (failed_repos, successful_repos_with_cls).
        failed_repos is a list of git repos where uploading failed.
        successful_repos_with_cls is a dict mapping repo path to the CL string.
    """
    # Gerrit has some pretty strict rate-limits, but uploading two repos at a
    # time should _hopefully_ not hit those. Even with a limit as low as two,
    # our throughput here is doubled.
    upload_semaphore = threading.BoundedSemaphore(2)

    def upload_one_repo(repo_subpath: Path) -> int:
        repo = android_tree / repo_subpath
        with upload_semaphore:
            cls_uploaded = git_utils.upload_to_gerrit(
                git_repo=repo,
                remote=git_utils.ANDROID_INTERNAL_REMOTE,
                branch=git_utils.ANDROID_MAIN_BRANCH,
                topic=topic,
                wip=True,
            )

        if not cls_uploaded:
            raise ValueError(f"Very strange: no CLs uploaded in {repo}")

        if len(cls_uploaded) != 1:
            logging.warning(
                "Uploaded %d CLs in %s somehow - ignoring all but the last",
                len(cls_uploaded),
                repo,
            )
        return cls_uploaded[-1]

    logging.info("Uploading %d CLs...", len(repos_to_upload))

    # Don't use `map`, since we filter on exceptions later.
    upload_futures = [
        thread_pool.submit(upload_one_repo, x) for x in repos_to_upload
    ]

    successful_uploads = {}
    exceptions = []
    for repo, upload_result in zip(repos_to_upload, upload_futures):
        if e := upload_result.exception():
            exceptions.append((repo, e))
        else:
            successful_uploads[repo] = f"ag/{upload_result.result()}"

    # List exceptions after all threads are done executing for clarity.
    for repo, e in exceptions:
        logging.error(
            "Exception caught uploading changes to %s", repo, exc_info=e
        )

    return [x for x, _ in exceptions], successful_uploads


def write_update_summary_file(
    target: Path,
    bug_number: int,
    exemptions: dict[str, RepoExemptionSummary],
) -> None:
    summary = ExemptionSummary(
        bug_number=bug_number,
        exemptions=exemptions,
    )
    summary.write_to_file(target)


# Types to help the readability of populate_and_write_summary.
_PerTargetDisabledWarnings = dict[str, list[str]]
_BpPath = str


def populate_and_write_summary(
    bug_number: int,
    update_summary_file: Path,
    updated_targets: dict[str, list[str]],
    uploaded_cls: dict[Path, str],
    file_to_repo: dict[Path, Path],
) -> None:
    """Populates and writes the exemption summary file."""
    # The type here is pretty unfortunate. The _values_ are per-target disabled
    # warnings, and the key is git repos.
    exemptions_per_git_repo: dict[
        str, dict[_BpPath, _PerTargetDisabledWarnings]
    ] = collections.defaultdict(lambda: collections.defaultdict(dict))
    for bp_path, updated_targets_in_bp in group_targets_by_bp_file(
        updated_targets
    ).items():
        repo_of_bp = str(file_to_repo[bp_path])
        exemptions_per_git_repo[repo_of_bp][str(bp_path)] = {
            target: updated_targets[target]
            for _, target in updated_targets_in_bp
        }

    final_exemptions = {}
    for repo_str, files_dict in exemptions_per_git_repo.items():
        updated_files = {}
        for bp_path_str, per_target_warnings in files_dict.items():
            updated_files[bp_path_str] = BpExemptionSummary(
                per_target_warnings=per_target_warnings
            )
        final_exemptions[repo_str] = RepoExemptionSummary(
            updated_files=updated_files,
            uploaded_cl=uploaded_cls.get(Path(repo_str)),
        )

    write_update_summary_file(
        update_summary_file,
        bug_number,
        exemptions=final_exemptions,
    )
    logging.info("Wrote summary file to %s", update_summary_file)


def parse_args(argv: list[str]) -> argparse.Namespace:
    """Parses and returns command-line arguments."""
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--android-tree",
        type=Path,
        help="""
        Android tree to modify. Meaningless if --dry-run is set. If not
        specified, autodetection from this script's directory will be attempted.
        """,
    )
    parser.add_argument(
        "--autobuild",
        action="store_true",
        help="""
        If passed, needed tooling (e.g., bpmodify) will be automatically built
        by this script. This may mess with your out/ dir, so is not the default.
        """,
    )
    parser.add_argument(
        "--bug-number",
        type=int,
        help="""
        Bug number to reference from bp files. Must be specified if --dry-run is
        not set. This bug should be directly related to the reason you're
        suppressing the warnings (e.g., an LLVM upgrade bug).
        """,
    )
    parser.add_argument(
        "--build-log",
        type=Path,
        required=True,
        help="""
        Path to the build log file to parse for warnings. For builds run
        remotely, this is the `build.log` artifact. For local builds, it's
        recommended you capture this via
        `rm -rf out; m -k checkbuild |& tee build.log`.

        Clean builds are recommended, since if your `m` invocation doesn't build
        a source file, it can't contain metadata about whether that source file
        fails to build.
        """,
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Don't apply exemptions; just print what would be done.",
    )
    parser.add_argument(
        "--debug", action="store_true", help="Enable debug logging."
    )
    parser.add_argument(
        "--keep-going",
        action="store_true",
        help="Do not fail if some files fail to be updated.",
    )
    parser.add_argument(
        "--branch-name",
        default="auto-suppress-warnings",
        help="Name of the branch to create in repos.",
    )
    parser.add_argument(
        "--update-summary-file",
        type=Path,
        help="""
        After making commits and (if applicable) uploading to Gerrit, write a
        JSON file to this Path listing all modified repositories.
        """,
    )
    parser.add_argument(
        "--upload-with-topic",
        help="""
        Upload all CLs applying suppressions using the given topic name. If you
        don't pass this, changes will simply be committed locally. If you do,
        they'll also be uploaded. Meaningless if --dry-run is passed.
        """,
    )
    opts = parser.parse_args(argv)

    if opts.android_tree:
        android_paths.assert_is_valid_android_tree_root(
            parser, opts.android_tree
        )

    if not opts.dry_run and not opts.bug_number:
        parser.error(
            "You must pass --bug-number if --dry-run is not specified."
        )

    return opts


def main(argv: list[str]) -> None:
    """Main entry point for the script."""
    opts = parse_args(argv)
    logging.basicConfig(
        format=">> %(asctime)s: %(levelname)s: %(filename)s:%(lineno)d: "
        "%(message)s",
        level=logging.DEBUG if opts.debug else logging.INFO,
    )

    android_tree: Path | None = opts.android_tree
    branch_name: str = opts.branch_name
    bug_number: int | None = opts.bug_number
    update_summary_file: Path | None = opts.update_summary_file
    dry_run: bool = opts.dry_run
    keep_going: bool = opts.keep_going
    upload_with_topic: str | None = opts.upload_with_topic

    # This script heavily uses `android_tree`'s textual representation (e.g.,
    # via `x.relative_to(android_tree)`. This may lead to failures if
    # `android_tree` has elements like symlinks, and if `x` has been
    # `resolve()`d. Resolve the Android tree early for simplicity and
    # consistency.
    if android_tree:
        android_tree = android_tree.resolve()

    with concurrent.futures.ThreadPoolExecutor() as thread_pool:
        autobuild_future: concurrent.futures.Future | None = None
        if (
            not dry_run
            and android_tree
            and bp_tools.need_autobuild(android_tree)
        ):
            if not opts.autobuild:
                sys.exit(
                    textwrap.dedent(
                        f"""\
                        No bpmodify/bpfmt binary and --autobuild not specified.
                        Please either build these in your android tree at
                        {android_tree} via `m blueprint_tools`, or pass
                        --autobuild (though note that `--autobuild` chooses its
                        own lunch combo, so may mess with your out/ dir).
                        """
                    ).rstrip()
                )
            logging.info(
                "Automatically building bp tooling in the background..."
            )

            # bp tooling takes minutes to build. Run it concurrently with log
            # parsing to speed things up a bit.
            autobuild_future = thread_pool.submit(
                bp_tools.autobuild_bp_tooling, android_tree
            )

        # Larger logs (~500MB) take a dozen seconds or so to parse.
        logging.info(
            "Parsing warnings from build log; this could take about a minute..."
        )
        warnings = parse_warning_reports(opts.build_log)
        if not warnings:
            logging.info("No fatal warning reports processed; quit")
            return

        logging.info("Found warnings to disable in %d targets.", len(warnings))
        if autobuild_future:
            # Since this runs `envsetup` and such, this can take quite a while.
            logging.info(
                "Waiting for bp tooling build, this could take a few minutes..."
            )
            autobuild_future.result()

        apply_results = apply_warning_exemptions(
            bug_number, warnings, android_tree, thread_pool, dry_run
        )

        if apply_results.update_failures:
            if not keep_going:
                sys.exit(
                    "Failed to add exemptions to "
                    f"{apply_results.update_failures} file(s); "
                    "see above logs. Use --keep-going to suppress this "
                    "behavior."
                )
            logging.warning(
                "Failed to add exemptions to %d file(s), but --keep-going was "
                "given.",
                apply_results.update_failures,
            )

        if not apply_results.successfully_updated_files:
            logging.info("No files got updated on disk; quit")
            return

        # These must be specified unless `dry_run` is passed, and `dry_run`
        # never updates any files.
        assert android_tree, "Files can't be updated without an Android tree"
        assert bug_number, "Files shouldn't be updated without a bug number"

        file_to_repo = map_files_to_git_repos(
            android_tree, thread_pool, apply_results.successfully_updated_files
        )

        repos_with_commit = commit_new_exemptions(
            bug_number,
            android_tree,
            thread_pool,
            updated_android_bp_files=apply_results.successfully_updated_files,
            branch_name=branch_name,
            file_to_repo=file_to_repo,
            updated_targets=apply_results.updated_targets,
        )
        logging.info(
            "Successfully made commits in %d repos", len(repos_with_commit)
        )

        uploaded_cls: dict[Path, str] = {}
        had_failures = bool(apply_results.update_failures)
        if upload_with_topic:
            failed_uploads, uploaded_cls = upload_all_new_exemptions(
                android_tree,
                thread_pool,
                upload_with_topic,
                repos_with_commit,
            )

            num_successful_uploads = len(uploaded_cls)
            logging.info(
                "Uploaded %d CLs with topic %s",
                num_successful_uploads,
                upload_with_topic,
            )
            if failed_uploads:
                had_failures = True
                logging.error(
                    "Uploading failed for repo(s):%s",
                    "".join(f"\n- {x}" for x in failed_uploads),
                )

        if apply_results.update_failures:
            logging.error(
                "As a reminder, adding exemptions failed on %d repo(s).",
                apply_results.update_failures,
            )

        if update_summary_file:
            populate_and_write_summary(
                bug_number,
                update_summary_file,
                apply_results.updated_targets,
                uploaded_cls,
                file_to_repo,
            )

        sys.exit(1 if had_failures else 0)
