# Copyright 2025 The ChromiumOS Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

"""Parses and applies warning exemptions from a build log.

For example, let's say that you had the build log of an Android build in
/tmp/build.log (in the form of a log generated by `m >& /tmp/build.log`, or
unpacking `verbose.log`, or similar).

If you invoke this script like:

$ py/bin/android_tools/parse_and_apply_warning_exemptions.py \
    --build-log=/tmp/build.log \
    --dry-run

It will parse your build log, and print exemptions that it would apply to
different packages. A future version of this script will actually _apply_ those.
"""

import argparse
import collections
import json
import logging
import os
from pathlib import Path
from typing import DefaultDict

from llvm_tools import warning_exemption


def infer_target_from_cmdline(command: list[str]) -> str | None:
    try:
        dash_o_index = command.index("-o")
    except ValueError:
        return None

    # Any well-formed compiler command will have a target after -o
    output_file = command[dash_o_index + 1]

    # Soong's output names look like:
    #   out/soong/.intermediates/
    #   ${target_path_from_top_of_tree}/
    #   ${variant}/
    #   obj/
    #   ${path_of_input_files_dir}/
    #   ${basename_of_input_file_no_ext}.o
    #
    # For example,
    # out/soong/.intermediates/bionic/libc/libc_bionic/
    #   android_x86_silvermont_static_apex10000_sabi/obj/bionic/libc/bionic/
    #   sigprocmask.o
    # has:
    #  - target_path_from_top_of_tree == //bionic/libc:libc_bionic
    #  - variant == android_x86_silvermont_static_apex10000_sabi
    #  - path_of_input_files_dir == obj/bionic/libc/bionic
    #  - basename_of_input_file_no_ext == sigprocmask
    prefix = "out/soong/.intermediates/"
    if not output_file.startswith(prefix):
        logging.warning(
            "Can't infer cmdline target; output file %s doesn't start with %s",
            output_file,
            prefix,
        )
        return None

    obj_location = output_file.find("/obj/")
    if obj_location == -1:
        logging.warning(
            "Can't infer cmdline target; output file %s has no /obj/",
            output_file,
        )
        return None

    target_path_and_variant = output_file[len(prefix) : obj_location]
    target_path_no_colon = os.path.dirname(target_path_and_variant)
    target_path, target_name = target_path_no_colon.rsplit("/", 1)
    return f"//{target_path}:{target_name}"


def parse_one_warning_report(
    report_line: str,
    report_line_number: int,
) -> tuple[str, warning_exemption.FatalWarningGroup] | None:
    report_json = json.loads(report_line)
    parsed_warnings = warning_exemption.scrape_fatal_warnings_from_stdout(
        report_json["stdout"]
    )

    # The shape of warnings_json is:
    # {
    #   "cwd": "/path/to/directory",
    #   "command": ["ccache", "full", "compile", "command"],
    #   "stdout": "stdout/stderr of the build",
    #   "parent_process_data": [
    #     {
    #       "invocation": ["parent", "process", "command"],
    #       "env": ["ENV1=", "ENV2=value", ""]
    #     }
    #   ]
    # }
    if not parsed_warnings:
        logging.warning(
            "Found no fatal warnings from report on line %d; ignoring",
            report_line_number,
        )
        return None

    target = infer_target_from_cmdline(report_json["command"])
    if not target:
        logging.warning(
            "Could not infer target from report on line %d; ignoring",
            report_line_number,
        )
        return None

    result_lines = {x for x, _ in parsed_warnings}
    result_names = {x for _, x in parsed_warnings}
    return target, warning_exemption.FatalWarningGroup(
        result_names, result_lines
    )


def parse_warning_reports(
    build_log: Path,
) -> dict[str, warning_exemption.FatalWarningGroup]:
    """Parses a build log for fatal warning reports.

    Returns:
        A dict of fatal warnings. Strings are paths to targets.
    """
    per_package_groups: DefaultDict[
        str, warning_exemption.FatalWarningGroup
    ] = collections.defaultdict(warning_exemption.FatalWarningGroup)
    # These are stored in the build log as single lines, like:
    # ```
    # <LLVM_NEXT_ERROR_REPORT>{"json": "object"}</LLVM_NEXT_ERROR_REPORT>
    # ```
    # The `{"json": "object"}` is what ChromeOS stores in individual warning
    # report files.
    werror_report_start = "<LLVM_NEXT_ERROR_REPORT>"
    werror_report_end = "</LLVM_NEXT_ERROR_REPORT>"
    with build_log.open(encoding="utf-8") as f:
        for line_number, line in enumerate(f, 1):
            line = line.strip()
            if not line.startswith(werror_report_start):
                continue

            if not line.endswith(werror_report_end):
                logging.warning(
                    "Line %d had error report start tag without end tag; "
                    "ignoring",
                    line_number,
                )
                continue

            logging.debug("Processing report on line %d", line_number)
            line = line[len(werror_report_start) : -len(werror_report_end)]
            parse_result = parse_one_warning_report(line, line_number)
            if not parse_result:
                # This should've been logged by the callee, so don't log.
                continue

            package, warnings_group = parse_result
            per_package_groups[package].add(warnings_group)
    return per_package_groups


def apply_warning_exemptions(
    warnings: dict[str, warning_exemption.FatalWarningGroup], dry_run: bool
) -> None:
    """Applies warning exemptions based on parsed warnings."""
    if dry_run:
        for target, warning_group in warnings.items():
            sorted_warning_list = sorted(warning_group.warning_names)
            logging.info(
                "dry-run: would have suppressed warnings %s in %s",
                sorted_warning_list,
                target,
            )
        return

    raise NotImplementedError("only --dry-run is implemented at present")


def parse_args(argv: list[str]) -> argparse.Namespace:
    """Parses and returns command-line arguments."""
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--build-log",
        type=Path,
        required=True,
        help="Path to the build log file to parse for warnings.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Don't apply exemptions; just print what would be done.",
    )
    parser.add_argument(
        "--debug", action="store_true", help="Enable debug logging."
    )
    return parser.parse_args(argv)


def main(argv: list[str]) -> None:
    """Main entry point for the script."""
    opts = parse_args(argv)
    logging.basicConfig(
        format=">> %(asctime)s: %(levelname)s: %(filename)s:%(lineno)d: "
        "%(message)s",
        level=logging.DEBUG if opts.debug else logging.INFO,
    )

    logging.info("Parsing warnings from build log; this could take a bit...")
    warnings = parse_warning_reports(opts.build_log)
    if not warnings:
        logging.info("No fatal warning reports processed; quit")
        return

    logging.info(
        "Found warnings to disable in %d targets. Doing so...", len(warnings)
    )
    apply_warning_exemptions(warnings, opts.dry_run)
